names:
- footer
- title
- marked_list
- footnote
- picture_signature
- graph
- table_signature
- header
- table
- formula
- numbered_list
- paragraph
- picture
nc: 13
test: test/test.json
train: train/train.json
