version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    volumes:
      - ./app:/project/app
      - pip-data:/usr/local/lib/python3.12/site-packages/
      - cache-data:/root/.cache
    working_dir: /project/app
    command: [ sh, -c, "tail -f /dev/null" ]


volumes:
  pip-data:
  cache-data: